### ISSUE TITLE
Left / right accessor keys for folder and photo controllers [$100 BOUNTY]

### ISSUE THREAD

**Issue by fulldecent** [fulldecent/cameralife#45]
These pages have logical previous / next pages:

* Page http://camera.phor.net/folder/2013/2013%20Random?start=40
  * Previous http://camera.phor.net/folder/2013/2013%20Random
  * Next http://camera.phor.net/folder/2013/2013%20Random?start=80

* Page http://camera.phor.net/photo/22532
  * Previous http://camera.phor.net/photo/22529
  * Next http://camera.phor.net/photo/22524
  * *Note: context is known from seeing this page http://camera.phor.net/folder/2015/2015-07-18%20Huan%20photo%20session*

**Work plan**

 - [x] Add `rel="prev"` and `rel="next"` links to these pages
 - [x] Allow left and right accessor keys to activate these two links
 - [x] Create test case using CasperJS that passes
 - [x] Integrate test case using Travis CI

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=31614571)](https://www.bountysource.com/issues/31614571-left-right-accessor-keys-for-folder-and-photo-controllers?utm_source=31614571&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by fulldecent** [comment]
Fixed with 367eb42a8e783c8ca18bd1e1e4274cf9792d3960
